# Generated by Django 5.0.7 on 2024-08-09 19:34

import authApi.models
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[(authApi.models.userType['STUDENT'], 'student'), (authApi.models.userType['EMPLOYEE'], 'employee'), (authApi.models.userType['INSTRUCTOR'], 'instructor'), (authApi.models.userType['ADMIN'], 'Admin')], max_length=40)),
                ('groups', models.ManyToManyField(related_name='authApi_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='authApi_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApi.user')),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('FIN', 'Finance'), ('HEALTH', 'Healthcare'), ('EDU', 'Education'), ('MINING', 'Mining'), ('TECHNOLOGY', 'Technology'), ('AGRICULTURE', 'Agriculture'), ('HOSPITALITY INDUSTRY', 'Hospitality'), ('FOOD INDUSTRY', 'Foodindustry'), ('TRANSPORTATION', 'Transportation'), ('FASHION', 'Fashion'), ('TELECOMMUNICATION', 'Telecommunication'), ('Professional, Scientific and Technical Services', 'Professionalscientifictechnicalservices'), ('Wholesale Trade', 'Wholesaletrade'), ('Manufacturing', 'Manufacturing'), ('BUSINESS', 'Business'), ('Infrastructure and Contractors', 'Infrastructureandcontractors')], max_length=255)),
                ('interests', models.ManyToManyField(related_name='emp_interests', to='authApi.interest')),
                ('skills', models.ManyToManyField(related_name='emp_skills', to='authApi.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApi.user')),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('FIN', 'Finance'), ('HEALTH', 'Healthcare'), ('EDU', 'Education'), ('MINING', 'Mining'), ('TECHNOLOGY', 'Technology'), ('AGRICULTURE', 'Agriculture'), ('HOSPITALITY INDUSTRY', 'Hospitality'), ('FOOD INDUSTRY', 'Foodindustry'), ('TRANSPORTATION', 'Transportation'), ('FASHION', 'Fashion'), ('TELECOMMUNICATION', 'Telecommunication'), ('Professional, Scientific and Technical Services', 'Professionalscientifictechnicalservices'), ('Wholesale Trade', 'Wholesaletrade'), ('Manufacturing', 'Manufacturing'), ('BUSINESS', 'Business'), ('Infrastructure and Contractors', 'Infrastructureandcontractors')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApi.user')),
                ('firstName', models.CharField(blank=True, max_length=50)),
                ('lastName', models.CharField(blank=True, max_length=50)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[(authApi.models.sexeEnum['MALE'], 'MALE'), (authApi.models.sexeEnum['FEMALE'], 'FEMALE')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('companyName', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('date_posed', models.DateField()),
                ('contract', models.CharField(choices=[(authApi.models.ContractTypes['PARTTIME'], 'part time'), (authApi.models.ContractTypes['FULLTIME'], 'full time'), (authApi.models.ContractTypes['FREELANCECONTRACT'], 'Freelance Contract'), (authApi.models.ContractTypes['FIXEDTERM'], 'Fixed-term')], max_length=50)),
                ('industry', models.CharField(choices=[('IT', 'IT'), ('FIN', 'FIN'), ('HEALTH', 'HEALTH'), ('EDU', 'EDU'), ('MINING', 'MINING'), ('TECHNOLOGY', 'TECHNOLOGY'), ('AGRICULTURE', 'AGRICULTURE'), ('HOSPITALITY INDUSTRY', 'HOSPITALITY INDUSTRY'), ('FOOD INDUSTRY', 'FOOD INDUSTRY'), ('TRANSPORTATION', 'TRANSPORTATION'), ('FASHION', 'FASHION'), ('TELECOMMUNICATION', 'TELECOMMUNICATION'), ('Professional, Scientific and Technical Services', 'Professional, Scientific and Technical Services'), ('Wholesale Trade', 'Wholesale Trade'), ('Manufacturing', 'Manufacturing'), ('BUSINESS', 'BUSINESS'), ('Infrastructure and Contractors', 'Infrastructure and Contractors')], max_length=100)),
                ('languages', models.CharField(choices=[(authApi.models.Language['ARABIC'], 'arabic'), (authApi.models.Language['FRENCH'], 'français'), (authApi.models.Language['ENGLISH'], 'english')], max_length=20)),
                ('skillCategory', models.ManyToManyField(related_name='job_skills', to='authApi.skill')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posting', to='authApi.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApi.user')),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('FIN', 'Finance'), ('HEALTH', 'Healthcare'), ('EDU', 'Education'), ('MINING', 'Mining'), ('TECHNOLOGY', 'Technology'), ('AGRICULTURE', 'Agriculture'), ('HOSPITALITY INDUSTRY', 'Hospitality'), ('FOOD INDUSTRY', 'Foodindustry'), ('TRANSPORTATION', 'Transportation'), ('FASHION', 'Fashion'), ('TELECOMMUNICATION', 'Telecommunication'), ('Professional, Scientific and Technical Services', 'Professionalscientifictechnicalservices'), ('Wholesale Trade', 'Wholesaletrade'), ('Manufacturing', 'Manufacturing'), ('BUSINESS', 'Business'), ('Infrastructure and Contractors', 'Infrastructureandcontractors')], max_length=255)),
                ('interests', models.ManyToManyField(related_name='std_interests', to='authApi.interest')),
                ('skills', models.ManyToManyField(related_name='std_skills', to='authApi.skill')),
            ],
        ),
    ]
