# Generated by Django 5.1 on 2024-08-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='languages',
            field=models.ManyToManyField(related_name='related_jobs', to='authApi.languages'),
        ),
    ]
