# Generated by Django 5.1 on 2024-08-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0002_alter_jobposting_languages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
    ]
