# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: |
      pip install -r requirements.txt  # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: python manage.py runserver

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Backend
    description: Port 8000 for the backend
    port: 8000
    onOpen: notify
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
