# Uncomment this line if you've created ".gitpod.Dockerfile" file to customize the workspace image. Lean more: https://www.gitpod.io/docs/configure/workspaces/workspace-image#using-a-custom-dockerfile
# image:
#   file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: | # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
      cd /workspace/talent-campus-lms/backend/api
      pip install -r requirements.txt
    command: |
      cd /workspace/talent-campus-lms/backend/api
      python manage.py runserver

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Backend
    description: Port 8000 for the backend
    port: 8000
    onOpen: notify
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
