# Generated by Django 5.1 on 2024-08-22 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='enrollement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='lms.enrollement'),
        ),
    ]
