# Generated by Django 5.0.7 on 2024-08-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_question_quiz_remove_questionchoice_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='qas',
            field=models.ManyToManyField(related_name='qa_questions', to='lms.qa'),
        ),
    ]
