# Generated by Django 5.1 on 2024-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='discussion_content',
            field=models.TextField(default=''),
        ),
    ]
