# Generated by Django 5.1 on 2024-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_remove_qa_question_question_qas'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='quizzes',
            field=models.ManyToManyField(related_name='assessements', to='lms.quiz'),
        ),
    ]
