# Generated by Django 5.0.7 on 2024-08-23 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_discussion_discussion_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussioncomment',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='discussion',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
